Molter73/balanpy

src/Balanpy.java

I deleted some spaces that were not needed.

Delete unneeded spaces

---

pom.xml
src/main/java/org/balanpy/ClimaClient.java
src/main/java/org/balanpy/ClimaController.java
src/main/java/org/balanpy/Main.java
src/main/resources/Clima.fxml

This PR adds the weather screen, all data is retrieved dynamically from wttr.in and displays the current temperatura as well as a graph with data for the current and next 2 days.

Add weather screen

---

src/main/java/org/balanpy/Usuario.java

Este PR agrega la interface Usuario, que será la base para comunicar la información del usuario de Balanpy entre el frontend y el backend.

Add Usuario interface

---

src/main/java/org/balanpy/Higiene.java
src/main/java/org/balanpy/Mascota.java

Se ha creado dos clases Java que comprenderán las interfaces para la mascota y la higiene, cada una de ellos con sus métodos Getters y Setters para poder extraer la información necesario del archivo JSON.

Interfaz Mascota e Higiene - In Progress

---

src/main/java/org/balanpy/Pulsaciones.java
src/main/resources/Pulsaciones.fxml

Se crea el archivo fxml y java para las pulsaciones, a falta de saber como enriquecer con datos el gráfico

Pulsaciones

---

src/main/java/org/balanpy/EditarPerfilUsuario.java
src/main/resources/EditarPerfilUsuario.fxml

se ha creado la rama editarperfilusuario y se ha creado el archivo fxml

Editar perfil usuario-agregar archivo fxml

---

src/main/java/org/balanpy/ConfiguracionHigiene.java
src/main/resources/ConfiguracionHigiene.fxml

Se ha creado la pantalla de configuración higiene

Pantalla configuración higiene

---

src/main/java/org/balanpy/Main.java

Este PR complementa #37, eliminando el código que estaba asociado con las pantallas eliminadas.

Se elimina código sin utilizar de Main.java

---

src/main/resources/BarraTareas.fxml

La barra de tareas se ha ajustado a 600px para que esté conforme a la cnfiguración de las pantallas.

Barra Tareas Mejora

---

src/main/java/org/balanpy/EditarPerfilUsuario.java
src/main/java/org/balanpy/UsuarioImpl.java
src/main/resources/EditarPerfilUsuario.fxml

Se ha introducido la accion de borrado del perfil del usuario, por tanto se ha modificado el archivo EditarPerfilUsuario, UsuarioImpl y el fxml de EditarPerfilUsuario, pero al final sale una excepcion

 Se modifica el .java y el fxml de EditarPerfilUsuario y el .java de UsuarioImpl.

---

.github/workflows/py-lint.yml
scripts/datos-aleatorios.py

Se agrega un `datos-aleatorios.py` que permite generar datos aleatorios. Dichos datos se generan como un array JSON que contiene objetos de la siguiente forma:
```JSON
{
"fecha": "2023/02/12T14:11:23",
"dato": 355
}
```
Estos array de datos pueden ser utilizados por la aplicación para representar mediciones de pulsaciones o temperatura independientemente.
Forma de uso del script:
```
usage: datos-aleatorios.py [-h] [-c COUNT] [-l LOWER] [-u UPPER] [-o OUTPUT]
options:
-h, --help            show this help message and exit
-c COUNT, --count COUNT
Number of events to generate
-l LOWER, --lower LOWER
Set the lower bound for generated date
-u UPPER, --upper UPPER
Set the lower bound for generated date
-o OUTPUT, --output OUTPUT
Specify file to write into
```
También se agrega un linter a la …

Script para generar datos aleatorios

---

src/main/resources/BarraTareas.fxml
src/main/resources/Clima.fxml
src/main/resources/ConfiguracionHigiene.fxml
src/main/resources/ConfiguracionMascota.fxml
src/main/resources/EditarPerfilUsuario.fxml
src/main/resources/Higiene.fxml
src/main/resources/PantallaInicio.fxml
src/main/resources/PerfilMascota.fxml
src/main/resources/PerfilUsuario.fxml
src/main/resources/PerfilVeterinario.fxml
src/main/resources/PortadaAplicacion.fxml
src/main/resources/Vacunas.fxml
src/main/resources/styles.css

También utilizamos styleClass para dar formato a elementos donde tiene sentido.

Unifica todos los estilos en un solo .css

---

src/main/java/org/balanpy/PerfilUsuario.java
src/main/resources/PerfilUsuario.fxml

Se ha arreglado el acceso a la pantalla de PerfilUsuario por un import mal puesto, se ha accedido desde PerfilUsuario a EditarPerfilUsuario y se ha intentado sacar por los Label los datos del Usuario pero sin exito.

 Accesos desde PerfilUsuario

---

src/main/java/org/balanpy/BarraSuperior.java
src/main/resources/BarraSuperior.fxml

Se ha creado una barra superior para todas las pantallas de la aplicación.

Barra Superior - In Progress

---

scripts/mascota_aleatoria.py

Está mal al posición en el JSON generado de la lista de productos no recomendables.

Mueve PNR dentro de higiene

---

src/main/resources/Temperaturas.fxml

Lo dejo en manos de alex que estaba retocando las pantallas y lo del css

 Se ha creado la pantalla de temperaturas

---

src/main/java/org/balanpy/ArchivosGenericosController.java
src/main/java/org/balanpy/LecturaArchivosGen.java
src/main/java/org/balanpy/PerfilUsuario.java
src/main/resources/FileView.fxml
src/main/resources/PerfilUsuario.fxml
src/main/resources/terminos-condiciones.txt

También arregla la lectura de archivos genericos.
Es un asco, pero funciona

Agrega terminos y condiciones

---

src/main/java/org/balanpy/Mascota.java
src/main/java/org/balanpy/MascotaImpl.java
src/main/java/org/balanpy/Mascotas.java
src/main/java/org/balanpy/PerfilMascota.java
src/main/java/org/balanpy/PortadaAplicacion.java
src/main/java/org/balanpy/Vacunas.java
src/main/resources/PerfilMascota.fxml

También agrega una clase auxiliar para permitir cargar los datos de las mascotas fácilmente.

Pantalla de PerfilMascota funcional

---

src/main/resources/Higiene.fxml
src/main/resources/styles.css

Se ha configurado los estilos de la pantalla higiene.

Pantalla Higiene Arreglada

---

src/main/resources/ConfiguracionMascota.fxml
src/main/resources/PerfilMascota.fxml
src/main/resources/PerfilUsuario.fxml
src/main/resources/PerfilVeterinario.fxml
src/main/resources/styles.css

Se han realizado arreglos mínimos en las pantallas ara una mejor visualización.

Arreglos Mínimos

---

scripts/mascota_aleatoria.py
src/main/java/org/balanpy/ConfiguracionMascota.java
src/main/java/org/balanpy/Mascota.java
src/main/java/org/balanpy/MascotaImpl.java
src/main/java/org/balanpy/Mascotas.java
src/main/java/org/balanpy/PerfilMascota.java
src/main/java/org/balanpy/PortadaAplicacion.java
src/main/resources/ConfiguracionMascota.fxml

Hace funcional la pantalla `ConfiguracionMascota.fxml`.

Configuración mascota
